config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

resources :movies do
  member do
    post :collect
    post :cancel
  end
  resources :reviews
end

namespace :account do
  resources :movies
  resources :reviews
end

root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews , dependent: :destroy
  validates :title, presence: true

  has_many :movie_relationships
  has_many :members, through: :movie_relationships, source: :user
end

app/models/movie_relationship.rb
class MovieRelationship < ApplicationRecord
  belongs_to :movie
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  validates :content, presence: true

  scope :recent, -> { order("created_at DESC")}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :movies
         has_many :reviews

         has_many :movie_relationships
         has_many :participated_movies, :through => :movie_relationships, :source => :movie

   def is_collect_of?(movie)
     participated_movies.include?(movie)
   end

   def collect!(movie)
     participated_movies << movie
   end

   def cancel!(movie)
     participated_movies.delete(movie)
   end

end

app/controllers/account/movies_controller.rb
class Account::MoviesController < ApplicationController
  before_action :authenticate_user!

  def index
    @movies = current_user.participated_movies
  end
  
end

app/controllers/account/reviews_controller.rb
class Account::ReviewsController < ApplicationController
  before_action :authenticate_user!
  def index
    @reviews = current_user.reviews
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user! ,only: [:new, :create, :edite, :update, :destroy, :collect, :cancel]
  before_action :find_movie_and_check_permission, only: [:edit, :update, :destroy]
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = @movie.reviews.recent.paginate(:page => params[:page], :per_page =>5)
  end

  def edit

  end

  def new
    @movie = Movie.new
end

def create
  @movie = Movie.new(movie_params)
  @movie.user = current_user

  if @movie.save
  current_user.collect!(@movie)
  redirect_to movies_path
else
  render :new
end
end

def update


if   @movie.update(movie_params)

  redirect_to movies_path, notice: "更新成功"
else
  render :edit
end
end

def destroy

  @movie.destroy
  flash[:alert] = "电影已删除"
  redirect_to movies_path
end

def collect
  @movie = Movie.find(params[:id])

  if !current_user.is_collect_of?(@movie)
    current_user.collect!(@movie)
    flash[:notice] = "收藏成功!"
  else
    flash[:warning] = "你已经收藏该影片"
  end

  redirect_to movie_path(@movie)
end

def cancel
  @movie = Movie.find(params[:id])

  if current_user.is_collect_of?(@movie)
    current_user.cancel!(@movie)
    flash[:notice] = "已取消收藏"
  else
    flash[:warning] = "你还未收藏该影片"
  end

  redirect_to movie_path(@movie)
end

private

def find_movie_and_check_permission
  @movie = Movie.find(params[:id])

  if current_user != @movie.user
    redirect_to root_path, alert: "你没有权限进行此操作"
  end
end

def movie_params
  params.require(:movie).permit(:title, :description)
end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  before_action :require_collect
  def new
    @movie = Movie.find(params[:movie_id])
    @review = Review.new
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.movie = @movie
    @review.user = current_user

    if @review.save
      redirect_to movie_path(@movie)
    else
    render  :new
  end

end


  def edit
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.find(params[:id])
    @review.movie = @movie
    @review.user = current_user
  end

  def show
  end

  def update
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.find(params[:id])
    @review.movie = @movie
    @review.user = current_user
    if
      @review.update(review_params)
      redirect_to movie_path(params[:movie_id]), notice:"修改评论成功！"
    else
      render :edit
    end

  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    @review = @movie.reviews.find(params[:id])
    @review.movie = @movie
    @review.user = current_user
    @review.destroy
     flash[:alert]= "已删除评论！"
    redirect_to (@movie)
  end



private

def review_params
params.require(:review).permit(:content,  )
end

def require_collect
  @movie = Movie.find(params[:movie_id])
  unless current_user.is_collect_of?(@movie)
    flash[:alert]= "你妹的！请先收藏该电影！！！"
      redirect_to (@movie)
  end
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
  end 
end

app/helpers/account/movies_helper.rb
module Account::MoviesHelper
end

app/helpers/account/reviews_helper.rb
module Account::ReviewsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end
end 

app/helpers/movies_helper.rb
module MoviesHelper
  def render_movie_description(movie)
    simple_format(movie.description)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def render_review_content(review)
    simple_format(review.content)
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
<% user_facing_flashes.each do |key, value| %>
<div class= "alert alert-dismissble alert-<%= flash_class(key) %>">
  <button class="close" data-dismiss="alert">x</button>
  <%= value %>

</div>
<% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px">
  <p class = "text-center">Copyright ©2017 Rails-test
    <br/> Made by ML 
</p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navitation">
  <div class="container-fluid">
    <!-- Brand and toggle get groupde for better mobile display -->

  <div class="navbar-header">
    <a class="navbar-brand" href="/">Rails-测试</a>
</div>

<!-- Collect the nav links, forms, and other content for toggling -->
<div class="collapse navbar-collapse" id= "bs-example-navbar-collapse-1">
  <ul class= "nav navbar-nav navbar-right">

<% if !current_user %>
    <li><%= link_to("注册", new_user_registration_path) %></li>
    <li><%= link_to("登录", new_user_session_path) %></li>
    <% else %>
    <li class="drapdown">
    <a href="#" class="drapdown-toggle" data-toggle="dropdown">
      Hi!, <%= current_user.email %>
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to("参与讨论的电影",account_movies_path)%></li>
      <li><%= link_to("发表过的评论", account_reviews_path)%></li>
      <li class="divider"></li>
      <li><%= link_to("退出",destroy_user_session_path, method: :delete) %></li>
  </ul>
    </li>
    <% end %>
</ul>
</div>
<!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class= "container-fluid">
      <%= render "common/navbar" %>
      <%= render "common/flashes" %>
    <%= yield %>
  </div>

  <%= render "common/footer" %>

  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
<% if @movie.errors.any? %>
<ul>
  <% @movie.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

影片名称：
<br>
<%= f.text_field :title %>
<br>
影片描述：
<br>
<%= f.text_area :description %>
<br>

<%= f.submit "提交", :disable_with => 'Submiting...' %>
<% end %>

app/views/movies/_form1.html.erb
<%=form_for @movie do |f| %>

<div class= "form-movie">
  <% if @movie.errors.any? %>
<ul>
  <% @movie.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
  <div class= "from-movie string optional">
    <%= f.label "影片名称：" , :class =>"string optional control-label" %>
    <%= f.text_field :title, :class =>"string optional form-control" %>
</div>

  <div class= "form-movie string optional">
    <%= f.label "影片描述：", :class=> "string optional control-label" %>
    <%= f.text_area :description, :class =>"string optional form-control" %>
</div>

</div>
<br>
<%= f.submit "提交", class: "btn btn-primary", data: { disable_with: "Submitting..."}%>
<% end %>

app/views/movies/_form2.html.erb
<%= simple_form_for @movie do |f| %>
<div class="form-movie">
  <%= f.input :title, input_html: {class: "form-control"} %>
  <%= f.input :description, input_html: {class: "form-control"} %>
</div>
<%= f.submit "提交",class: "btn btn-primary", data: {disable_with: "Submiting..."}%>
<% end %>

app/views/movies/_movie_item.html.erb
<tr>
  <td>#</td>
  <td><%= link_to(movie.title, movie_path(movie)) %></td>
  <td><%= render_movie_description(movie) %></td>
  <td><%= movie.user.email %></td>
  <td>
    <% if current_user && current_user == movie.user %>
    <%= link_to("编辑", edit_movie_path(movie), class: "btn btn-sm btn-default") %>
    <%= link_to("删除", movie_path(movie),    class: "btn btn-sm btn-default",
                 method: :delete,  data: { confirm: "确定删除吗?"})%>
<% end %>
</td>

</tr>

app/views/movies/edit.html.erb
<div class= "col-md-4 col-md-offset-4">
  <h2>编辑电影版</h2>

  <hr>

<%= render "form1" %>
</div>

app/views/movies/index.html.erb
<div class= "col-md-12">
  <div class= "movie">
    <%= link_to("添加新电影", new_movie_path, class: "btn btn-primary pull-right" )%>
</div>
<table class= "table table-hover">
  <thead>
    <tr>
      <td>#</td>
      <td>电影名称</td>
      <td>描述</td>
      <td>创建者</td>
  </tr>
</thead>
<tbody>
<%= render :partial =>"movie_item", :collection => @movies, :as => :movie %>

</tbody>
</table>
</div>

app/views/movies/new.html.erb
<div class= "col-md-4 col-md-offset-4">
  <h2>新增电影版</h2>
<hr>

<%= render "form1" %>
</div>

app/views/movies/show.html.erb
<div class = "col-md-12">
  <div class = "movie">

    <span class="pull-right">
      <% if current_user && current_user.is_collect_of?(@movie) %>
        <label class="label label-success">已收藏</label>
        <%= link_to("取消收藏", cancel_movie_path(@movie), method: :post, class: "btn btn-default" ) %>
          <% else %>
          <label class="label label-warning">还未收藏-收藏后可评论</label>
          <%= link_to("收藏该影片",collect_movie_path(@movie), method: :post, class: "btn btn-default") %>
      <% end %>
  </span>
 <% if current_user && current_user.is_collect_of?(@movie) %>
    <%= link_to("编写评论", new_movie_review_path(@movie), class: "btn btn-default pull-right")%>
<% end %>
    <% if current_user && current_user == @movie.user %>
    <%= link_to("编辑",edit_movie_path(@movie), class: "btn btn-primary pull-right" )%>
    <% end %>
</div>
<h2><%= @movie.title %></h2>
<p><%= @movie.description %></p>
<%= render "reviews/index"%>

app/views/reviews/_form.html.erb
<%= form_for @review, url: movie_review_path do |f| %>

<div class= "form-review">
  <% if @review.errors.any? %>
<ul>
  <% @review.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
  <div class= "from-movie string optional">
    <%= f.label "评论内容：" , :class =>"string optional control-label" %>
    <%= f.text_area :content, :class =>"string optional form-control" %>
</div>
</div>




<br>
<%= f.submit "提交", class: "btn btn-primary", data: { disable_with: "Submitting..."}%>
<% end %>

app/views/reviews/_index.html.erb
<table class= "table">
  <thead>
    <tr>
      <th>发表者</th>
      <th>评论内容</th>
      <th>发表时间</th>
  </tr>
</thead>

<tbody>
  <% @reviews.each do |review| %>
  <tr>
    <td><%= review.user.email %></td>
    <td><%= render_review_content(review) %></td>
    <td><%= review.created_at %></td>
    <td>
      <% if current_user && current_user == review.user %>
    <%= link_to("编辑", edit_movie_review_path(review.movie, review),class: "btn btn-sm btn-default")%>
    <%= link_to("删除", movie_review_path(review.movie, review),class: "btn btn-sm btn-default", method: :delete,data:{confirm:"确定删除吗？"}) %>
    <% end %>
  </td>
</tr>
<% end %>
</tbody>
</table>

<div class="text-center">
  <%= will_paginate @reviews %>
</div>
</div>

app/views/reviews/edit.html.erb
<div class= "col-md-4 col-md-offset-4">
  <h2>修改评论</h2>



       <hr/>

<%= render "form" %>
</div>

app/views/reviews/new.html.erb
<h2 class= "text-center">新增评论</h2>

<div class="col-md-4 col-md-offset-4">
  <%= simple_form_for [@movie,@review] do |f| %>
  <div class="form_movie">
    <%= f.input :content, input_html: {class: "form-control"} %>
</div>
<div class="form-actions">
  <%= f.submit "提交", disable_with: "Submiting...", class: "btn btn-primary"%>
</div>
<% end %>
</div>

app/views/welcome/index.html.erb
<h1>Hello World and ML!</h1>